### ISSUE TITLE
BoardDisplay.py program cannot connect to Arduino board

### ISSUE THREAD

**Issue by ShadowJie** [DonovanZhu/9DoF_MARG_Madgwick_Filter#1]
Hello DonovanZhu. 
I have some problems when I use your respository. After I download MPU9250_Madgwick.ino into Arduino, I want to show the gesture by using BoardDisplay.py file, I have configured the 'COM' and baudRate, but it still show "Trying to connect to: COM9 at 115200 BAUD. Failed to connect with COM9 at 115200 BAUD."  (I use serialport  COM9 ,baudrate is 115200). I  use UNO R3. All libraries are installed in the python project.

**Comment by DonovanZhu** [comment]
Hi ShadowJie, sorry for the late reply!
I use a Arduino UNO and change the baudrate to 115200, then test the BoardDisplay.py file, and it works well. Is there any detail you can provide? How did you know the COM number?

**Comment by ShadowJie** [comment]
Hi DonovanZhu!
Thank you for your reply! I know my COM number in Arduino IDE, it shows my serial port is  COM9. I think my configue is correct, but the Pycharm still shows "Trying to connect to: COM9 at 115200 BAUD. Failed to connect with COM9 at 115200 BAUD." So can you send me your changed project(for UNO and boud 115200Hz) to my e-maill(maopijie@outlook.com). I want to try again. Thank you.

**Comment by DonovanZhu** [comment]
The python program for UNO has no difference with the orignal one except the port name (for me it is "COM 5") and baud rate (changed to 115200). 
To check the connection between UNO and computer, the Arduino program on UNO is simply setting the Serial Baud rate to 115200 in the setup() function without any other commands.
Would you mind just writing a simple demo in your UNO like I did?

**Comment by DonovanZhu** [comment]
I tried the python program with a computer that has never run this program before. The program still worked.

**Comment by ShadowJie** [comment]
Thank you DonovanZhu!
I found the problem. In Pycharm I installed serial library but without installed pyserial. After I installed the pyserial library, it can work now. But my MPU9250 rotation direction is inconsistent with the model in Python. I think it's the x  y z direction problem. I will try.
