### ISSUE TITLE
How to output 0 when reset Arduino?

### ISSUE THREAD

**Issue by ShadowJie** [DonovanZhu/9DoF_MARG_Madgwick_Filter#2]
Hi DonovanZhu!
Sorry to disturb you again. I have a new problem. I want the position output attitude angle to be 0 when reset MCU every time, that is, the attitude when reset is the initial attitude (yaw pitch roll output is 0) instead of the relative earth coordinate system output angle, and then the attitude is changed relative to the initial attitude.  I feel confused.  What modifications should I make？
Thank you!

**Comment by DonovanZhu** [comment]
Sorry, this algorithm can only provide the attitude relative to the earth, since it uses gravity and magnetic north to build the world frame.  Maybe you can try recording the initial attitude, then comparing the estimated attitude with the initial one and then calculating the difference.

**Comment by ShadowJie** [comment]
> Sorry, this algorithm can only provide the attitude relative to the earth, since it uses gravity and magnetic north to build the world frame. Maybe you can try recording the initial attitude, then comparing the estimated attitude with the initial one and then calculating the difference.

OK, Thank you DonovanZhu!
